### ISSUE TITLE
Caught an Exception

### ISSUE THREAD

**Issue by earthmutant** [vinci6k/dnd5e#1]
Hey Vinci6k! Sorry I haven't been so active. I've tried out your new facelift build and haven't been able to get it to work, could you check this out for me?

```
[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\plugins\command.py", line 164, in load_plugin
    plugin = self.manager.load(plugin_name)
  File "..\addons\source-python\packages\source-python\plugins\manager.py", line 207, in load
    plugin._load()
  File "..\addons\source-python\packages\source-python\plugins\instance.py", line 74, in _load
    self.module = import_module(self.import_name)
  File "..\addons\source-python\plugins\dnd5e\dnd5e.py", line 84, in <module>
    from .core.config import bot_classes
  File "..\addons\source-python\plugins\dnd5e\core\config.py", line 7, in <module>
    from ..info import info

ImportError: cannot import name 'info'
```

**Comment by vinci6k** [comment]
Whoops, forgot to include the [\_\_init\_\_.py](https://github.com/vinci6k/dnd5e/blob/master/addons/source-python/plugins/dnd5e/__init__.py) file in the dnd5e folder, my bad! 😅
